In [42]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import classification_report
from imblearn.ensemble import BalancedRandomForestClassifier
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
#Read in the CSV and read in the data
df = pd.read_csv("Resources/neighborhood_tier.csv")
df = df.drop(columns=['Unnamed: 0','postal_code'])

In [3]:
df.head()

Mexican  Chinese  Italian  Cafe  Fastfood  Mexican_stars  Chinese_stars  \
0      1.0      1.0      1.0   2.0       1.0            4.5            3.5   
1      1.0      3.0      1.0   3.0       3.0            2.0            3.3   
2      0.0      0.0      3.0   1.0       0.0            0.0            0.0   
3      0.0      0.0      0.0   1.0       0.0            0.0            0.0   
4      0.0      0.0      1.0   0.0       1.0            0.0            0.0   

   Italian_stars  Cafe_stars  Fastfood_stars  Mexican_review_count  \
0            3.5         4.5             5.0                  13.0   
1            3.5         3.3             2.7                  17.0   
2            4.0         4.0             0.0                   0.0   
3            0.0         4.5             0.0                   0.0   
4            4.0         0.0             4.0                   0.0   

   Chinese_review_count  Italian__review_count  Cafe_review_count  \
0                  25.0                    7.0               14.0   
1                  74.0                    5.0              150.0   
2                   0.0                   71.0               16.0   
3                   0.0                    0.0               20.0   
4                   0.0                   16.0                0.0   

   Fastfood_review_count Neighborhood Tiers  
0                    9.0              Tier2  
1                  109.0              Tier2  
2                    0.0              Tier2  
3                    0.0              Tier3  
4                   20.0              Tier3

In [4]:
# Convert string columns to numbers
le = LabelEncoder()
df['Neighborhood Tiers'] = le.fit_transform(df['Neighborhood Tiers'])

In [5]:
df.head()

Mexican  Chinese  Italian  Cafe  Fastfood  Mexican_stars  Chinese_stars  \
0      1.0      1.0      1.0   2.0       1.0            4.5            3.5   
1      1.0      3.0      1.0   3.0       3.0            2.0            3.3   
2      0.0      0.0      3.0   1.0       0.0            0.0            0.0   
3      0.0      0.0      0.0   1.0       0.0            0.0            0.0   
4      0.0      0.0      1.0   0.0       1.0            0.0            0.0   

   Italian_stars  Cafe_stars  Fastfood_stars  Mexican_review_count  \
0            3.5         4.5             5.0                  13.0   
1            3.5         3.3             2.7                  17.0   
2            4.0         4.0             0.0                   0.0   
3            0.0         4.5             0.0                   0.0   
4            4.0         0.0             4.0                   0.0   

   Chinese_review_count  Italian__review_count  Cafe_review_count  \
0                  25.0                    7.0               14.0   
1                  74.0                    5.0              150.0   
2                   0.0                   71.0               16.0   
3                   0.0                    0.0               20.0   
4                   0.0                   16.0                0.0   

   Fastfood_review_count  Neighborhood Tiers  
0                    9.0                   1  
1                  109.0                   1  
2                    0.0                   1  
3                    0.0                   2  
4                   20.0                   2

In [6]:
# Create the features
X = df.drop(columns='Neighborhood Tiers')
X.head()

Mexican  Chinese  Italian  Cafe  Fastfood  Mexican_stars  Chinese_stars  \
0      1.0      1.0      1.0   2.0       1.0            4.5            3.5   
1      1.0      3.0      1.0   3.0       3.0            2.0            3.3   
2      0.0      0.0      3.0   1.0       0.0            0.0            0.0   
3      0.0      0.0      0.0   1.0       0.0            0.0            0.0   
4      0.0      0.0      1.0   0.0       1.0            0.0            0.0   

   Italian_stars  Cafe_stars  Fastfood_stars  Mexican_review_count  \
0            3.5         4.5             5.0                  13.0   
1            3.5         3.3             2.7                  17.0   
2            4.0         4.0             0.0                   0.0   
3            0.0         4.5             0.0                   0.0   
4            4.0         0.0             4.0                   0.0   

   Chinese_review_count  Italian__review_count  Cafe_review_count  \
0                  25.0                    7.0               14.0   
1                  74.0                    5.0              150.0   
2                   0.0                   71.0               16.0   
3                   0.0                    0.0               20.0   
4                   0.0                   16.0                0.0   

   Fastfood_review_count  
0                    9.0  
1                  109.0  
2                    0.0  
3                    0.0  
4                   20.0

In [7]:
X.describe()

Mexican     Chinese     Italian        Cafe    Fastfood  \
count  650.000000  650.000000  650.000000  650.000000  650.000000   
mean     9.324615    9.161538    9.512308    9.501538    9.352308   
std      9.654949    9.426223    9.738207   10.023893    9.593295   
min      0.000000    0.000000    0.000000    0.000000    0.000000   
25%      3.000000    2.000000    2.000000    2.000000    2.000000   
50%      7.000000    6.000000    7.000000    7.000000    7.000000   
75%     13.000000   13.750000   14.000000   14.000000   14.000000   
max     65.000000   76.000000   70.000000   85.000000   72.000000   

       Mexican_stars  Chinese_stars  Italian_stars  Cafe_stars  \
count     650.000000     650.000000     650.000000  650.000000   
mean        3.173692       3.126769       3.139538    3.101077   
std         1.150748       1.162998       1.125659    1.187317   
min         0.000000       0.000000       0.000000    0.000000   
25%         3.100000       3.100000       3.100000    3.000000   
50%         3.500000       3.500000       3.400000    3.500000   
75%         3.800000       3.800000       3.800000    3.800000   
max         5.000000       4.500000       5.000000    5.000000   

       Fastfood_stars  Mexican_review_count  Chinese_review_count  \
count      650.000000            650.000000            650.000000   
mean         3.203846           1045.983077           1003.472308   
std          1.081758           2586.085769           2219.333592   
min          0.000000              0.000000              0.000000   
25%          3.100000             84.000000             77.250000   
50%          3.500000            361.500000            339.000000   
75%          3.800000           1097.250000           1078.250000   
max          5.000000          44897.000000          35056.000000   

       Italian__review_count  Cafe_review_count  Fastfood_review_count  
count             650.000000         650.000000             650.000000  
mean             1092.963077        1084.538462            1047.383077  
std              2376.422163        2300.539738            2322.551384  
min                 0.000000           0.000000               0.000000  
25%                74.250000          76.250000              83.250000  
50%               371.500000         347.500000             365.500000  
75%              1118.250000        1101.500000            1080.500000  
max             31144.000000       31298.000000           34536.000000

In [8]:
#Create target variable
y = df['Neighborhood Tiers']

In [9]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({1: 239, 2: 125, 0: 123})

In [10]:
# Creating StandardScaler instance
scaler = StandardScaler()

# Fitting Standard Scaler
X_scaler = scaler.fit(X_train)

# Scaling data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

### Label encoder has coded the tiers into the following values:
* Tier1 = 3
* Tier2 = 1
* Tier3 = 2

# Create a logistic regression model

In [11]:
# Logistic Regression
classifier = LogisticRegression(solver='lbfgs', random_state=1, max_iter = 200)
classifier

LogisticRegression(max_iter=200, random_state=1)

In [12]:
# Train the data
classifier.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=200, random_state=1)

In [13]:
# Predict outcomes for test data set
predictions = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(20)

Prediction  Actual
385           1       1
242           1       1
600           1       2
579           1       1
475           1       1
465           1       1
214           1       1
589           1       1
116           0       0
634           1       2
148           1       1
23            1       0
647           0       2
236           1       1
101           1       0
66            1       1
436           1       2
358           1       1
224           1       1
88            1       1

In [14]:
#Validate the model using the test data
accuracy_score(y_test, predictions)

0.5398773006134969

In [15]:
#Calculate the Balanced Accuracy score
y_pred = classifier.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.3772464522674783

In [16]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[ 8, 31,  2],
       [ 6, 79,  2],
       [ 1, 33,  1]], dtype=int64)

In [46]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.59      0.54        41
           1       0.58      0.41      0.48        87
           2       0.30      0.46      0.36        35

    accuracy                           0.47       163
   macro avg       0.46      0.49      0.46       163
weighted avg       0.50      0.47      0.47       163



# Create Balanced Random Forest Classifier

In [18]:
# Resample the training data with the BalancedRandomForestClassifier
model = BalancedRandomForestClassifier(n_estimators=100, random_state=1) 
model.fit(X_train_scaled, y_train)

BalancedRandomForestClassifier(random_state=1)

In [19]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)

balanced_accuracy_score(y_test, y_pred)

0.5133271923852244

In [20]:
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).head(20)

Prediction  Actual
385           2       1
242           2       1
600           2       2
579           0       1
475           2       1
465           2       1
214           2       1
589           2       1
116           0       0
634           1       2
148           2       1
23            1       0
647           0       2
236           0       1
101           0       0
66            0       1
436           2       2
358           1       1
224           2       1
88            2       1

In [21]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[27,  6,  8],
       [28, 22, 37],
       [ 5,  8, 22]], dtype=int64)

In [45]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.59      0.54        41
           1       0.58      0.41      0.48        87
           2       0.30      0.46      0.36        35

    accuracy                           0.47       163
   macro avg       0.46      0.49      0.46       163
weighted avg       0.50      0.47      0.47       163



# Create Easy Ensemble AdaBoost Classifier

In [23]:
# Train the EasyEnsembleClassifier
model = EasyEnsembleClassifier(n_estimators=100, random_state=1) 
model.fit(X_train_scaled, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [24]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test_scaled)

balanced_accuracy_score(y_test, y_pred)

0.48543393808322316

In [25]:
pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).head(20)

Prediction  Actual
385           1       1
242           2       1
600           1       2
579           1       1
475           2       1
465           2       1
214           2       1
589           1       1
116           0       0
634           1       2
148           2       1
23            1       0
647           0       2
236           0       1
101           0       0
66            1       1
436           1       2
358           1       1
224           2       1
88            2       1

In [26]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[24, 12,  5],
       [19, 36, 32],
       [ 5, 14, 16]], dtype=int64)

In [44]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.59      0.54        41
           1       0.58      0.41      0.48        87
           2       0.30      0.46      0.36        35

    accuracy                           0.47       163
   macro avg       0.46      0.49      0.46       163
weighted avg       0.50      0.47      0.47       163



# Create Gradient Boosting Classifier

In [34]:
# Create a classifier object
learning_rates = [0.05, 0.1, 0.25, 0.5, 0.75, 1]
for learning_rate in learning_rates:
    classifier = GradientBoostingClassifier(n_estimators=20,
                                            learning_rate=learning_rate,
                                            max_features=5,
                                            max_depth=3,
                                            random_state=0)
    # Fit the model
    classifier.fit(X_train_scaled, y_train)
    print("Learning rate: ", learning_rate)

    # Score the model
    print("Accuracy score (training): {0:.3f}".format(
        classifier.score(
            X_train_scaled,
            y_train)))
    print("Accuracy score (validation): {0:.3f}".format(
        classifier.score(
            X_test_scaled,
            y_test)))
    print()

Learning rate:  0.05
Accuracy score (training): 0.593
Accuracy score (validation): 0.534

Learning rate:  0.1
Accuracy score (training): 0.692
Accuracy score (validation): 0.521

Learning rate:  0.25
Accuracy score (training): 0.842
Accuracy score (validation): 0.521

Learning rate:  0.5
Accuracy score (training): 0.910
Accuracy score (validation): 0.540

Learning rate:  0.75
Accuracy score (training): 0.957
Accuracy score (validation): 0.479

Learning rate:  1
Accuracy score (training): 0.990
Accuracy score (validation): 0.466



In [35]:
# Choose a learning rate and create classifier
classifier = GradientBoostingClassifier(n_estimators=20,
                                        learning_rate=0.5,
                                        max_features=5,
                                        max_depth=3,
                                        random_state=0)

# Fit the model
classifier.fit(X_train_scaled, y_train)

# Make Prediction
predictions = classifier.predict(X_test_scaled)
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).head(20)

Prediction  Actual
385           1       1
242           2       1
600           1       2
579           1       1
475           1       1
465           1       1
214           1       1
589           1       1
116           0       0
634           1       2
148           2       1
23            1       0
647           0       2
236           0       1
101           0       0
66            1       1
436           1       2
358           1       1
224           1       1
88            2       1

In [36]:
# Calculating the accuracy score
acc_score = accuracy_score(y_test, predictions)
print(f"Accuracy Score : {acc_score}")

Accuracy Score : 0.5398773006134969


In [38]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[24, 12,  5],
       [19, 36, 32],
       [ 5, 14, 16]], dtype=int64)

In [43]:
# Print the imbalanced classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.59      0.54        41
           1       0.58      0.41      0.48        87
           2       0.30      0.46      0.36        35

    accuracy                           0.47       163
   macro avg       0.46      0.49      0.46       163
weighted avg       0.50      0.47      0.47       163

